// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc199.Offseason2017;

import org.usfirst.frc199.Offseason2017.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.*;
import org.usfirst.frc199.Offseason2017.subsystems.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
	
    public JoystickButton toggleDriveTypeButton;
    public Joystick leftJoystick;
    public JoystickButton switchToHighGearButton;
    public JoystickButton switchToLowGearButton;
    public Joystick rightJoystick;
    public JoystickButton toggleGearIntakeButton;
    public JoystickButton gearIntakeUpButton;
    public JoystickButton gearIntakeDownAndRunButton;
    public Joystick manipulator;

    public OI() {
    	
//    	manipulator
        manipulator = new Joystick(2);
        gearIntakeDownAndRunButton = new JoystickButton(manipulator, 1);
        gearIntakeDownAndRunButton.whenPressed(new GearIntakeDownandRun());
        gearIntakeUpButton = new JoystickButton(manipulator, 1);
        gearIntakeUpButton.whenPressed(new GearIntakeUp());
        toggleGearIntakeButton = new JoystickButton(manipulator, 1);
        toggleGearIntakeButton.whenPressed(new ToggleGearIntake());
        
//      right joystick
        rightJoystick = new Joystick(1);
        switchToLowGearButton = new JoystickButton(rightJoystick, 1);
        switchToLowGearButton.whenPressed(new SwitchtoLowGear());
        switchToHighGearButton = new JoystickButton(rightJoystick, 1);
        switchToHighGearButton.whenPressed(new SwitchtoHighGear());
        
//      left joystick
        leftJoystick = new Joystick(0);
        toggleDriveTypeButton = new JoystickButton(leftJoystick, 1);
        toggleDriveTypeButton.whenPressed(new ToggleDriveType());


        // SmartDashboard Buttons
        SmartDashboard.putData("Switch to High Gear", new SwitchtoHighGear());
        SmartDashboard.putData("Switch to Low Gear", new SwitchtoLowGear());
        SmartDashboard.putData("Toggle Drive Type", new ToggleDriveType());
        SmartDashboard.putData("Toggle Gear Intake", new ToggleGearIntake());
        SmartDashboard.putData("Gear Intake Up", new GearIntakeUp());
        SmartDashboard.putData("Gear Intake Down and Run", new GearIntakeDownandRun());
    }
    
    /**
     * Gets the left joystick.
     * @return the left joystick
     * */
    public Joystick getLeftJoystick() {
        return leftJoystick;
    }
    
    /**
     * Gets the right joystick.
     * @return the right joystick
     * */
    public Joystick getRightJoystick() {
        return rightJoystick;
    }
    
    /**
     * Gets the manipulator.
     * @return the manipulator
     * */
    public Joystick getManipulator() {
        return manipulator;
    }
}

